### ISSUE TITLE
Kan dere sjekke hvorfor jeg fortsatt har tilgang til alt og ligger inne i teamet?

### ISSUE THREAD

**Issue by Jesperpaulsen** [navikt/modiapersonoversikt-api#1247]
Kan det være at det er noe feil? :D Har fortsatt skrivetilgang til alle repoer og får notifications på PRer. Vil dere dobbeltsjekke med Kathrine at alt stemmer?

**Comment by LudvigHz** [comment]
hmm ja sånn skal det jo ikke være. Skal dobbeltsjekke asap!

**Comment by Jesperpaulsen** [comment]
hva ble konklusjonen @LudvigHz?

**Comment by LudvigHz** [comment]
Du er fjernet fra github nå i alle fall, men gi med en lyd om det er noe mer som må gjøres noe med :)
